# Generated by Django 3.2.7 on 2021-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_next_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
