# Generated by Django 3.2.7 on 2021-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='date',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
