# Generated by Django 3.2.7 on 2021-09-28 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_background_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_date', message='The date format is yyyy-mm or yyyy', regex='^(\\d{4}\\-\\d{2})|\\d{4}$')]),
        ),
    ]
