# Generated by Django 3.2.7 on 2021-10-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_medicaltreatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
    ]
