# Generated by Django 3.2.7 on 2021-10-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_password_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
