export const GET_PATIENTS = 'GET_PATIENTS';
export const GET_PAGINATOR_PATIENTS = 'GET_PAGINATOR_PATIENTS';
export const SEARCH_PATIENTS = 'SEARCH_PATIENTS';
export const GET_PATIENT = 'GET_PATIENT';
export const GET_SESSION_PATIENT = 'GET_SESSION_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const ADD_PATIENT = 'ADD_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';

export const GET_ERRORS = 'GET_ERRORS';
export const GET_ALERT = 'GET_ALERT'

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LAST_SUCCESS_ACTION = 'LAST_SUCCESS_ACTION';

// Action Patient
export const GET_BACKGROUND = 'GET_BACKGROUND';
export const ADD_BACKGROUND = 'ADD_BACKGROUND';
export const DELETE_BACKGROUND = 'DELETE_BACKGROUND';
export const UPDATE_BACKGROUND = 'UPDATE_BACKGROUND';

export const GET_MEDICAL_HISTORIES = 'GET_MEDICAL_HISTORIES';
export const ADD_MEDICAL_HISTORIES = 'ADD_MEDICAL_HISTORIES';
export const DELETE_MEDICAL_HISTORIES  = 'DELETE_MEDICAL_HISTORIES';
export const UPDATE_MEDICAL_HISTORIES  = 'UPDATE_MEDICAL_HISTORIES';